### ISSUE TITLE
Alignment of elements in InputGroups

### ISSUE THREAD

**Issue by andydandy74** [MostafaElAyoubi/Data-shapes#27]
Hi Mostafa,
Really like the new input groups.

I would suggest that TextNotes nested in InputGroups should align with other form elements in that group:
![grafik](https://user-images.githubusercontent.com/3014437/30366236-b7dd881e-986a-11e7-8a87-33c2249b3305.png)
![grafik](https://user-images.githubusercontent.com/3014437/30366247-c2c5149a-986a-11e7-80a8-b50507c3c3fd.png)

Also, it would be great if inputs could be expanded to full width if InputName is empty:
![grafik](https://user-images.githubusercontent.com/3014437/30366454-5c72b28c-986b-11e7-83c6-918b4ec33ab4.png)
![grafik](https://user-images.githubusercontent.com/3014437/30366458-630e8206-986b-11e7-8c62-1337ceccd55e.png)

**Comment by MostafaElAyoubi** [comment]
Hi @andydandy74 ,
I forgot to handle this apparently ! :) 
I just fixed the first part of the problem : 
![image](https://user-images.githubusercontent.com/20224923/30583716-0dfe357e-9d28-11e7-9c47-18185434d1e3.png)
I also like what you're suggesting. I modified the code so that inputs without input names expand to the full width. He're how the inputs look like with/without inputnames in/out of inputgroups:

buttons: 
![image](https://user-images.githubusercontent.com/20224923/30585666-ea163bba-9d2d-11e7-9a94-49ef2062fa5f.png)
dropdowns : 
![image](https://user-images.githubusercontent.com/20224923/30585724-10ece22a-9d2e-11e7-8e0c-24ee83ec1d7d.png)
listviews:
![image](https://user-images.githubusercontent.com/20224923/30585824-5049ce74-9d2e-11e7-87c6-266866ea8893.png)
radiobuttons:
![image](https://user-images.githubusercontent.com/20224923/30585858-680a0ab0-9d2e-11e7-9248-2c1af58f0a93.png)
textboxes: 
![image](https://user-images.githubusercontent.com/20224923/30585950-b07de3f2-9d2e-11e7-8e64-e07970d8b70b.png)
sliders:
![image](https://user-images.githubusercontent.com/20224923/30586208-833db54c-9d2f-11e7-91a3-9f2b39e5c02c.png)

It's all in version 2017.9.1 of the package

**Comment by andydandy74** [comment]
Cool. One other thought: maybe it would make sense to use an empty string as default value for all InputName inputs instead of "Default".

**Comment by MostafaElAyoubi** [comment]
Yes that's what I did actually. And I test wether the inputname is an empty string or not to set the width and position of the input.

**Comment by andydandy74** [comment]
Ah okay, great. That'll save me some empty string nodes in the future. :-)
